### PR TITLE
Added C++ Client

### PR DESCRIPTION
**Pull request by cshreyastech**
Added C++ Client Support

### CODE REVIEW

**Comment by adnanmunawar** [comment]
Thanks for the PR Shreyas, this looks great. I noticed that some files have a slightly different license header (using "www.aimlab.wpi.edu" which is an invalid link I think). Also, let's make the year consistent between all the files, some say 2019, some 2020, and so on. We can set them all to be 2019-2021. Can you update all the files to be consistent?

**Comment by cshreyastech** [comment]
Thanks, Adnan for the review. Will work on addressing the comments.

**Comment by cshreyastech** [comment]
Updated.

**Comment by adnanmunawar** [comment]
Thanks for all the changes. I noticed that there were some library files in the bin folder that were deleted as part of this PR, can you please restore them?

**Comment by cshreyastech** [comment]
Add them back. I thought they gets generated on building in the corresponding OS. Sorry for removing them.

**Pull request merged**
