### PR TITLE
Fix checking Package_FOUND variables

### PR DESCRIPTION
**Pull request by kschwan**
Hi,
I tried building AMBF on Ubuntu 22.04 (without ROS/catkin) and got an error when checking *the value* of catkin_FOUND. If packages are *not* found, Package_FOUND variables do not exist and trying to check their value will cause cmake to return an error. This PR has a small patch to check the existence of the Package_FOUND variables and not their value.

### CODE REVIEW

**Comment by adnanmunawar** [comment]
Thanks for the PR Kim. Happy to hear that you made it to work with Ubuntu 22.04. I shall test these modifications on Ubuntu 20.04 to verify that they also work there and then integrate the PR.

Out of curiosity, as far as I know, one has to build ROS1 from source on Ubuntu 22.04, is that what you did?

**Comment by kschwan** [comment]
Sorry I kinda forgot replying here. I didn't build ROS1 from source, I just built AMBF without ROS support (I suppose?).

**Comment by kschwan** [comment]
> Thanks for the PR Kim. Happy to hear that you made it to work with Ubuntu 22.04. I shall test these modifications on Ubuntu 20.04 to verify that they also work there and then integrate the PR.
> 
> Out of curiosity, as far as I know, one has to build ROS1 from source on Ubuntu 22.04, is that what you did?

Just to satisfy your curiosity: I now did compile ROS Noetic on Ubuntu 22.04 and it seems to work fine with AMBF also :)

**Comment by adnanmunawar** [comment]
Thanks for checking this, Kim. I also tested the PR on Ubuntu 20.04 and it works. We can probably address the issue of C++17 compilation in a new PR.

**Pull request merged**
