### PR TITLE
Added a Github Action to Build App on Push Using Docker [WORK IN PROGRESS]

### PR DESCRIPTION
**Pull request by pacarvalho**
This is an exploration of using Github Actions to build and test the application. Note: We can also use Github Actions natively without creating our own Docker image. But having a Docker image may be useful for newcomers who don't want to build on their system. 

Related to #62 #53 

To run the Action locally use https://github.com/nektos/act

Results on Github:

image

### CODE REVIEW

**Comment by adnanmunawar** [comment]
This is nice. Thanks for looking into this. Is this ready to be merged or still work in progress?

**Comment by pacarvalho** [comment]
@adnanmunawar I believe we should do a few more things:
1. Include the build in a different OS. This one uses Ubuntu 18.04 with Melodic ROS. We could have Ubuntu 16.04 with an order version of ROS.
2. Include at least 1 test so that it demonstrates how the testing should work. Are there any tests written in the program so far? If so, how do I run them? If not, any preference on how to do it or should I use my imagination?

However, none of the above impede this from being merged. If merged as is, it will show the checkmark (or red X) near the latest commit from each push regarding if it built or not successfully (might require going into the repo settings and adding the check). So, if you prefer, you can merge as is and I can create a separate PR for the tests. Just let me know which method you prefer. 

Sample of checkmark and build error below:

image

**Comment by DhruvKoolRajamani** [comment]
I'm working on adding apt and pip requirements, will share that image first and also add a few tests.

**Comment by DhruvKoolRajamani** [comment]
I believe we can close this and look at #70 instead since it has additional features for training required by @VigneshManoj and @cshreyastech.

**Comment by pacarvalho** [comment]
Closed in pro of https://github.com/WPI-AIM/ambf/pull/70

**Pull request closed without merging**
