### PR TITLE
calculates the joint velcotity

### PR DESCRIPTION
**Pull request by nag92**
Uses a deque to store the previous joint positions and does a weighted average on the velocity to calculate the joint velocity.

### CODE REVIEW

**Comment by nag92** [comment]
1. I am using wall_time. should I use get_sim_step(). when I looked at that number it is an interger. get_wall_time() returns a float()
2. that was an error. fixing it now.

**Comment by nag92** [comment]
This uses a linear weighting with the highest weight on the newest value.

**Comment by adnanmunawar** [comment]
You should use the sim_time, not sim_step. The sim_step is the number of simulation iterations and should be an int.

**Comment by nag92** [comment]
made the switch to sim time

**Comment by adnanmunawar** [comment]
Great. I went over the code and I like the overall implementation. However, the only thing I am concerned about is the velocity calculation in the ros_cb methods. Is there a way we could move the velocity computation outside? I wouldn't mind a separate thread or even not computing the velocity until a user specifically asks for it using a method. That being said, we can still fill the queue of joint positions and timestamps for the computation of velocity in the ros_cb.

**Comment by nag92** [comment]
That should not be too hard to move the calculation to a separate thread. I have done this multiple times in my own projects.  I would prefer this over calculating the vel when the user wants it. I have to look into two different queue methods. I want to make sure I use the one that is tread safe. 
Do we also want a method of controlling the queue size?

**Comment by adnanmunawar** [comment]
Sure, that should be fine. But keep in mind that you shouldn't have to make a very long implementation as we might transmit the velocity from the C++ side at some point in the future. And yes, the ability to control the queue size is ideal.

**Comment by nag92** [comment]
So I am having a lot of trouble getting the tread to work. The initialization step is failing. So since it sounds like this is going to be moved into the C++ I am going to have it calculated when you get to get the velocity.

**Comment by nag92** [comment]
This is not ideal but if we are going to move it higher up it will work for now. I have a hack work around for the window size. I make the queue size large but only access the queue for a set window size. This is because copying the data to a new queue which can result in complications So haveing queue size cost more memory it is more efficient for calculations and requires no copying.

**Comment by nag92** [comment]
Are You moving the joint velocity calculation to the C++ side?

**Comment by adnanmunawar** [comment]
Please see the latest commit. It contains several other additions as well. The code at your end won't see any change since the way you retrieve objects from the Python client remains the same. However, instead of getting an Object instance, you will get a RigidBody instance, which has all the same methods as Object and a few extra methods such as velocity get/set.

**Comment by nag92** [comment]
got it, that was a huge update, Once it works again 20.04. ill start testing everything. will probably have to rewrite some of my code to work with the changes but only at the low level.

**Pull request closed without merging**
