### PR TITLE
Raven2 yaml File Update & C++ Client ROS Node

### PR DESCRIPTION
**Pull request by melodysu83**
(1) Raven2 blender yaml file: 
The inertial parameters (position offsets and masses) are updated based on actual RAVEN specifications. The orientation part is not yet included.

(2) AMBF_controller module: 
     - This is a sample C++ ROS node that interacts with Raven2 from the AMBF_simulator. 
     - Raven kinematics are included so it supports both joint level and cartesian motion commands. 
     - Cartesian/Joint level test scripts available through easy keyboard control. 
     - Multicamera feature: Functions to generate random camera motion for each view point and navigate cameras back to their home poses.

### CODE REVIEW

**Comment by adnanmunawar** [comment]
Hey Melody, thanks again for the PR. The additions are very useful and IMO the stepping stone for creating controllers for different robots (dVRK, Neuro Robot etc). There are just some edits that I have in mind so far. 

1. I like the idea of using scripts wherever we can. Let's tweak the [Compile and Run Script](https://github.com/melodysu83/ambf/blob/master/CompileAndRunScript.sh) to create the build and bin directories in a relative directory. For instance, I could have placed this code in `/home/robot/my_account/melodys_fork/` folder and I would want the build and bin to be relative rather than absolute as I might already have an ambf install in the home folder.

2. Let's make sure that in [Cmake](https://github.com/melodysu83/ambf/blob/master/CMakeLists.txt#L308), the lines 308 and 311 are included only if we are on Linux machines and ROS install is found as we won't be able to build it on Mac OS. Checkout lines between 102-126 for the current implementation of including ROS modules only if we are on Linux.

3. This one is more of an organizational suggestion. How about we create a subfolder in ambf_controllers and name it raven or raven2 or whatever and put the existing contents of ambf_controllers in there. I say this because we might have a dvrk controller, then a neuro robot controller and so on so forth. What do you think?

**Comment by melodysu83** [comment]
Hey Adnan,
Thanks for the feedback, that makes sense! 
I've made some changes according to your suggestions. 
Let me know what you think and if there's anything else we could modify.

**Comment by adnanmunawar** [comment]
Great so far. Just a few more minor changes
 
1. I think I mistakenly asked you to put the `add_subdirectory (${PROJECT_SOURCE_DIR}/ambf_simulator)` on line 317 in the `if (${CMAKE_SYSTEM_NAME} MATCHES Linux)` conditional block, my bad. We always want to build ambf_simualtor. So let's take it out of the conditional block. And let's move `add_subdirectory (${PROJECT_SOURCE_DIR}/ambf_controller)` on line 320 to line 104 such that:

```diff
if (${CMAKE_SYSTEM_NAME} MATCHES Linux)
    find_package(catkin COMPONENTS
      roscpp
    )
    if (${catkin_FOUND})
        message("-- *** FOUND ROS ON THIS MACHINE, ENABLING SUPPORT FOR AMBF_ROS MODULES")
        add_subdirectory(${PROJECT_SOURCE_DIR}/ambf_ros_modules)
+       add_subdirectory(${PROJECT_SOURCE_DIR}/ambf_controller)
```

2. Let's also move the specific comments on launching the ambf_controller from the root README file to a separate README file placed in the `ambf_controllers` subfolder as it is optional.

3. How about making another world.launch file called `ambf_models/descriptions/world/raven_world.yaml` where we can put your modified world file with extra cameras and naming convention so that we can use it whenever we want but keep the default file (after restoring it) that existed beforehand. We can then modify the [launch](https://github.com/melodysu83/ambf/blob/master/ambf_models/descriptions/launch.yaml) file such that
we can have a commented `raven_world.launch`.
``` diff
world config: ./world/world.yaml
+#world config: ./world/raven_world.yaml 
color config: ./color/colors.yaml
input devices config: ./input_devices/input_devices.yaml
```

**Comment by melodysu83** [comment]
Hi Adnan,
Thanks for the suggestions. I've made a few edits according to our discussion. 
1. I am not able to put "add_subdirectory(${PROJECT_SOURCE_DIR}/ambf_controller)" right around line 104 without some dependencies issue when building. So seems like there are some AMBF Controller dependencies that is defined later in the "CMakeList.txt" file. So I still put it at line 310-318 but pulled the AMBF simulator outside of the if condition so it will always build.
2. A separate "readme.md" file is now created in the AMBF Controller subfolder.
3. A separate "raven_world.yaml" file is created and users have the option to uncomment their choice of world config in the "launch.yaml" file.
The repo is also merged and modified according to your most recent commit. Let me know your thoughts. And thanks again for your help!

**Comment by adnanmunawar** [comment]
This looks great Melody. Merging it to the master branch now.

**Pull request merged**
