### PR TITLE
AMBF C++ client

### PR DESCRIPTION
**Pull request by nag92**
Add support for a C++ client. The client matchs the python implementation.
The RBDL+Controller code as been moved to its own repo, however the history remains fro tracking and documentation.

### CODE REVIEW

**Comment by nag92** [comment]
@cshreyastech main contributor

**Comment by cshreyastech** [comment]
@adnanmunawar Gtest was used to test client implementation. Seems like github doest have this package which causes this failure. Let us know if we would like to remove this?

**Comment by adnanmunawar** [comment]
Based on a quick glance, these are some of the comments that I have.
1. The `Readme.md` is in conflict with the latest `Readme.md`. Please fix this.
2. Let's create a separate `contributor.md` file and put the contributors there.
3. I would get rid of GTest from the code, readme, etc. at the moment.
4. The ambf_client_app's file naming convention seems different than ambf_client? Not sure if we need this to be called ambf_client_app or generally be part of ambf, it seems too specific to dvrk and basically a C++ version of the Python code.
5. The ambf_client_test project class could be cleaned up and improved. Also no need for a redundant header file (here and in general).
6. Why is the ambf_client part of the ambf_controller folder?
7. Why are the methods named as they are in `ambf_client.cpp` (getACamera, getAActuator and so on)?
8. Get rid of the package.xml files as they are not required.
9. It appears that while copying over the structure from the python client, some empty/useless C++ files were created, e.g. `rl_test.cpp` and `rl_test.h`. Moreover, files like `utilites.cpp` may not be required as Eigen (C++) already offers the required functionality.
10. Please remove all the files that are not part of the PR, there are more than 30 files of this nature.
11. Since the client, app and tests are ROS dependent, only include these in the `CMakeLists.txt` if the target OS is Linux. Check the rest of the file to know where to add these two lines.
12. I am often guilty of this myself, but we should not put code with commented lines of basic code into commits and PR on the main branch. This gives the impression that the personal debug version of code is being pushed to the main repo.

**Comment by nag92** [comment]
@adnanmunawar I am not sure why it is showing changes to some of the files. I pulled them from the ambf-1.0 branch. I also compared the sections that show have changes.

**Comment by nag92** [comment]
going to reopen a new PR

**Comment by adnanmunawar** [comment]
Thanks for cleaning this up. There are some files that can still be reverted/removed as they are not significant to the PR. These include: 
.github/workflows/main.yml
blender-kuka.yaml
devel-training-gpu.Dockerfile
devel-training.Dockerfile
devel.Dockerfile
apt-requirements
pip-requirements

**Comment by nag92** [comment]
The blender-kuka file was purposely changed it now as the inertia tags for the control package.  I would like to keep it as it is in our branch. I can revert the other files

**Comment by adnanmunawar** [comment]
@nag92. Oh that is great that you updated the file, however, better to create a separate PR for it.

**Comment by nag92** [comment]
@adnanmunawar  the changes have been pushed

**Comment by nag92** [comment]
@adnanmunawar what else needs to be done?

**Comment by adnanmunawar** [comment]
I removed the package.xml and it broke the build. I am going to fix it and then merge

**Pull request merged**
